class TaskNotFoundError(Exception):
    pass


class ValidationError(Exception):
    pass

